package com.jbde.constants;

public enum CinematographerRoles {
	TRAINEE_CINEMATOGRAPHER,
	ASSOCIATE_CINEMATOGRAPHER,
	SENIOR_CINEMATOGRAPHER,
	LEAD_CINEMATOGRAPHER,
	SENIOR_LEAD_CINEMATOGRAPHER,
	EXECUTIVE_CINEMATOGRAPHER,
	SENIOR_EXECUTIVE_CINEMATOGRAPHER
}
