package com.jbde.constants;

public enum DirectorRoles {
	TRAINEE_DIRECTOR,
	ASSOCIATE_DIRECTOR,
	SENIOR_DIRECTOR,
	LEAD_DIRECTOR,
	SENIOR_LEAD_DIRECTOR,
	EXECUTIVE_DIRECTOR,
	SENIOR_EXECUTIVE_DIRECTOR
}
