package com.jbde.constants;

public enum ManagerRoles {
	TRAINEE_MANAGER,
	ASSOCIATE_MANAGER,
	SENIOR_MANAGER,
	LEAD_MANAGER,
	SENIOR_LEAD_MANAGER,
	EXECUTIVE_MANAGER,
	SENIOR_EXECUTIVE_MANAGER,
	PRODUCTION_MANAGER,
	ADMIN_MANAGER,
	GENERAL_MANAGER
}
